kind: pipeline
type: docker
name: linux

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: golang:1.12
  commands:
  - go test -cover ./...
  volumes:
  - name: go
    path: /go

- name: build
  image: golang:1.12
  commands:
  - sh scripts/build.sh
  volumes:
  - name: go
    path: /go
  when:
    event:
    - push
    - tag

- name: publish_amd64
  image: plugins/docker
  pull: if-not-exists
  settings:
    repo: drone/drone-runner-docker
    auto_tag: true
    auto_tag_suffix: linux-amd64
    dockerfile: docker/Dockerfile.linux.amd64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    ref:
    - refs/heads/master
    - refs/tags/*

- name: publish_arm
  image: plugins/docker
  pull: if-not-exists
  settings:
    repo: drone/drone-runner-docker
    auto_tag: true
    auto_tag_suffix: linux-arm
    dockerfile: docker/Dockerfile.linux.arm
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    ref:
    - refs/heads/master
    - refs/tags/*

- name: publish_arm64
  image: plugins/docker
  pull: if-not-exists
  settings:
    repo: drone/drone-runner-docker
    auto_tag: true
    auto_tag_suffix: linux-arm64
    dockerfile: docker/Dockerfile.linux.arm64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    ref:
    - refs/heads/master
    - refs/tags/*

volumes:
- name: go
  temp: {}

---
kind: pipeline
type: ssh
name: windows-1903

platform:
  os: windows

server:
  host:
    from_secret: windows_server_1903
  password:
    from_secret: windows_password
  user:
    from_secret: windows_username

steps:
- name: build_latest
  environment:
    VERSION: 1903
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
  commands:
  - powershell.exe scripts/windows/latest.ps1
  when:
    event: [ push ]

- name: build_tag
  environment:
    VERSION: 1903
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
  commands:
  - powershell.exe scripts/windows/tag.ps1
  when:
    event: [ tag ]

depends_on:
- linux

trigger:
  ref:
  - refs/heads/master
  - refs/tags/*

---
kind: pipeline
type: ssh
name: windows-1809

platform:
  os: windows

server:
  host:
    from_secret: windows_server_1809
  password:
    from_secret: windows_password
  user:
    from_secret: windows_username

steps:
- name: build_latest
  environment:
    VERSION: 1809
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
  commands:
  - powershell.exe scripts/windows/latest.ps1
  when:
    event: [ push ]

- name: build_tag
  environment:
    VERSION: 1809
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
  commands:
  - powershell.exe scripts/windows/tag.ps1
  when:
    event: [ tag ]

depends_on:
- linux

trigger:
  ref:
  - refs/heads/master
  - refs/tags/*

---
kind: pipeline
type: ssh
name: windows-1909

platform:
  os: windows

server:
  host:
    from_secret: windows_server_1909
  password:
    from_secret: windows_password
  user:
    from_secret: windows_username

steps:
- name: build_latest
  environment:
    VERSION: 1909
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
  commands:
  - powershell.exe scripts/windows/latest.ps1
  when:
    event: [ push ]

- name: build_tag
  environment:
    VERSION: 1909
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
  commands:
  - powershell.exe scripts/windows/tag.ps1
  when:
    event: [ tag ]

depends_on:
- linux

trigger:
  ref:
  - refs/heads/master
  - refs/tags/*

---
kind: pipeline
type: docker
name: manifest

steps:
- name: manifest
  image: plugins/manifest
  settings:
    spec: docker/manifest.tmpl
    auto_tag: true
    ignore_missing: true
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username

depends_on:
- windows-1903
- windows-1809
- windows-1909

trigger:
  ref:
  - refs/heads/master
  - refs/tags/*

