# escape=`
FROM mcr.microsoft.com/windows/nanoserver:1809
USER ContainerAdministrator

EXPOSE 3000
ENV GODEBUG=netdns=go
ENV DRONE_PLATFORM_OS windows
ENV DRONE_PLATFORM_ARCH amd64
ENV DRONE_PLATFORM_KERNEL 1809

ADD release/windows/amd64/drone-runner-docker.exe C:/drone-runner-docker.exe
ENTRYPOINT [ "C:\\drone-runner-docker.exe" ]